/*PERMISOS*/
GRANT INSERT, SELECT ON BD_BUILDOC.comentario_archivo to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.comentario_tarea to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT, UPDATE (arcNombre_Original, arcRuta, arcTipo, arcTamaño, arcEtiqueta, fk_id_carpeta) ON BD_BUILDOC.ga_archivo to 'Administrador', 'Coordinador', 'Trabajador'; 
GRANT INSERT, SELECT ON BD_BUILDOC.ga_archivoversion to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.ga_archivos_gii_incidentes to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.ga_archivos_gii_inspecciones to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.ga_archivos_gii_seguimientos to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.ga_archivos_gt_tareas to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT, UPDATE (carNombre, carRuta, carEtiqueta, carDescripcion, fk_id_proyecto) ON BD_BUILDOC.ga_carpeta to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT, UPDATE (cliNombre, cliCorreo, cliTelefono) on BD_BUILDOC.ga_cliente to 'Administrador';
GRANT SELECT on BD_BUILDOC.ga_cliente to 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.ga_proyecto to 'Administrador';
GRANT SELECT, UPDATE (proNombre, proDescripcion, proRuta) ON BD_BUILDOC.ga_proyecto to 'Coordinador';
GRANT SELECT ON BD_BUILDOC.ga_proyecto to 'Trabajador';
GRANT INSERT, SELECT, UPDATE (incEstado) ON BD_BUILDOC.gii_incidente to 'Administrador', 'Coordinador';
GRANT INSERT, SELECT ON BD_BUILDOC.gii_incidente to 'Trabajador';
GRANT INSERT, SELECT, UPDATE (insEstado, insFecha_inicial, insPeriodicidad, insFecha_final) ON BD_BUILDOC.gii_inspeccion to 'Administrador', 'Coordinador';
GRANT SELECT ON BD_BUILDOC.gii_inspeccion to 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.gii_involucrado to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.gii_seguimiento to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.gii_resultadoinspeccion to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT ON BD_BUILDOC.gii_resultadoinspeccion_ga_archivos to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, SELECT, UPDATE (fasNombre, fasDescripcion, fasEstado) ON BD_BUILDOC.gt_fase to 'Administrador', 'Coordinador';
GRANT SELECT ON BD_BUILDOC.gt_fase to 'Trabajador';
GRANT INSERT, SELECT, UPDATE (tarNombre, tarDescripcion, tarPrioridad, tarEstado, tarFecha_limite, fk_id_fase) ON BD_BUILDOC.gt_tarea to 'Administrador', 'Coordinador';
GRANT SELECT, UPDATE (tarEstado) ON BD_BUILDOC.gt_tarea to 'Trabajador';
GRANT SELECT ON BD_BUILDOC.rol to 'Administrador';
GRANT INSERT ON BD_BUILDOC.usuario to 'Administrador';
GRANT SELECT, UPDATE (usuNombre_EPS, usuNombre_ARL, usuMunicipio, usuDireccion_residencia, usuContrasenia, usuTelefono, usuCorreo, usuRuta_Firma) ON BD_BUILDOC.usuario to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT ON BD_BUILDOC.usuarios_gii_inspecciones to 'Administrador', 'Coordinador';
GRANT SELECT ON BD_BUILDOC.usuarios_gii_inspecciones to 'Administrador', 'Coordinador', 'Trabajador';
GRANT SELECT ON BD_BUILDOC.usuarios_gt_tareas to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT, UPDATE (fk_id_usuario, fk_id_tarea) ON BD_BUILDOC.usuarios_gt_tareas to 'Administrador', 'Coordinador';
GRANT SELECT ON BD_BUILDOC.usuarios_proyectos to 'Administrador', 'Coordinador', 'Trabajador';
GRANT INSERT ON BD_BUILDOC.usuarios_proyectos to 'Administrador', 'Coordinador';
GRANT INSERT ON BD_BUILDOC.usuarios_roles to 'Administrador';
GRANT SELECT ON BD_BUILDOC.usuarios_roles to 'Administrador', 'Coordinador', 'Trabajador';